# Generated by Django 5.1 on 2024-11-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_checkoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='boys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boys', to=settings.AUTH_USER_MODEL, verbose_name='boys'),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
