# Generated by Django 5.1 on 2024-11-03 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0011_alter_pet_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_number', models.CharField(blank=True, max_length=255, null=True)),
                ('advance_amount', models.IntegerField(blank=True, null=True)),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_app.pet')),
            ],
        ),
    ]
