# Generated by Django 5.1 on 2024-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0012_pet_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_book',
            name='balance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
